version: '3'
services:

  educa:
      image: registry.digitallearning.gmbh/educa/educa-lrs/main:latest
      restart: unless-stopped
      ports:
        - 80:80
      environment:
        - TZ=Europe/Berlin
      volumes:
        - ./storage/logs:/usr/share/nginx/html/storage/logs
        - ./storage/app:/usr/share/nginx/html/storage/app
        - ./db:/var/lib/mysql
        - ./.env_educa:/usr/share/nginx/html/.env


